name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been there for quite a while. Try emailing the maintainers if the issue persists.'
        stale-pr-message: 'Convert this into a draft if you are still working on it.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
